name: Go

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f

    - name: Set up Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        go-version: 1.18

    - name: Build
      env:
        CGO_ENABLED: 0
        GOOS: linux      
      run: go build --tags static_all -v -o ./bin/netpolicy cmd/netpolicy/main.go

    #- name: Test
    #  run: go test -v ./pkg/controller
