name: Publish to pkg.go.dev

on:
  push:
    tags:
      - v0.**

permissions:
  contents: read

jobs:
  publish_on_pkg_go_dev:
    name: publish a new version in pkg.go.dev
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version: 1.19

      - name: Publish on pkg.go.dev
        run: GOPROXY=proxy.golang.org go list -m github.com/np-guard/netpol-analyzer@${{ github.ref_name }}
